#:import color kivy.utils.get_color_from_hex
#:import sp kivy.metrics.sp

#:import chain itertools.chain

#:import cos math.cos
#:import sin math.sin
#:import pi math.pi
#:import Graph kivy.garden.graph

#:set title_color '353535'
#:set title_underline '353535'
#:set subtitle_color '353535'   # サブタイトルの背景カラー
#:set subtitle_underline '353535'
#:set default_color (0, 0, 0, 1)
#:set background_color 'ffffff' # 背景カラー
#:set content_color '000000'
#:set font_size 35

