TextWidget: # ルートに追加


<TextWidget@Widget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        
        # ラベル
        Label:
            size_hint_y: 0.7
            id: label1
            font_size: 68
            text: 'test4'
            
        BoxLayout:
            size_hint_y: 0.3
            Button:
                id: button1
                text: "morning"
                font_size: 68
                on_press: lable_txt = 'morning'
            Button:
                id: button2
                text: "day"
                font_size: 68
                #on_press: root.buttonClicked2()  # ボタンをクリックした時

            Button:
                id: button3
                text: "night"
                font_size: 68
                #on_press: root.buttonClicked3()  # ボタンをクリックした時
                

            Button:
                id: button4
                text: "night2"
                font_size: 68
                #on_press: root.buttonClicked3()  # ボタンをクリックした時
                
