<GraphWidget>:
    id: graph_plot3
    #Graph2:
    Graph:
        id: graph_plot
        background_color: (0.5, 0.5, 0.5, 1)
        xlabel: 'X'
        ylabel: 'Y'
        x_ticks_minor: 5
        x_ticks_major: 25
        y_ticks_major: 1
        y_grid_label: True
        x_grid_label: True
        padding: 5
        x_grid: True
        y_grid: True
        xmin: -0
        xmax: 100
        ymin: -1
        ymax: 1
        size: root.size